export const matchTimes = [
  {
    id: 1,
    matchId: 1,
    phase: "FIRST_HALF",
    start: "15:01",
    end: "15:46",
    extraMinutes: 1,
    homeGoals: 1,
    awayGoals: 0,
  },
  {
    id: 2,
    matchId: 1,
    phase: "SECOND_HALF",
    start: "16:00",
    end: "16:48",
    extraMinutes: 3,
    homeGoals: 2,
    awayGoals: 1,
  },
  {
    id: 3,
    matchId: 2,
    phase: "FIRST_HALF",
    start: "15:01",
    end: "15:46",
    extraMinutes: 1,
    homeGoals: 0,
    awayGoals: 0,
  },
  {
    id: 4,
    matchId: 2,
    phase: "SECOND_HALF",
    start: "16:00",
    end: "16:48",
    extraMinutes: 3,
    homeGoals: 1,
    awayGoals: 0,
  },
  {
    id: 5,
    matchId: 3,
    phase: "FIRST_HALF",
    start: "15:01",
    end: "15:46",
    extraMinutes: 1,
    homeGoals: 5,
    awayGoals: 5,
  },
  {
    id: 6,
    matchId: 3,
    phase: "SECOND_HALF",
    start: "16:00",
    end: "16:48",
    extraMinutes: 3,
    homeGoals: 5,
    awayGoals: 5,
  },
];
