export const matches = [
  {
    id: 1,
    leagueId: 1,
    homeTeamId: 1,
    awayTeamId: 2,
    date: "2026-07-21",
    time: "15:00",
    location: "Cair",
    round: 12,
    officials: [
      { userId: 2, role: "REFEREE" },
      { userId: 5, role: "ASSISTANT_1" },
    ],
    status: "PLAYED",
    mupDocument: null,
  },
  {
    id: 2,
    leagueId: 1,
    homeTeamId: 3,
    awayTeamId: 1,
    date: "2026-07-25",
    time: "16:00",
    location: "Pirot",
    round: 13,
    officials: [
      { userId: 2, role: "REFEREE" },
      { userId: 5, role: "ASSISTANT_1" },
    ],
    status: "PLAYED",
    mupDocument: null,
  },
  {
    id: 3,
    leagueId: 1,
    homeTeamId: 2,
    awayTeamId: 3,
    date: "2026-07-25",
    time: "12:00",
    location: "Leskovac",
    round: 13,
    officials: [{ userId: 2, role: "REFEREE" }],
    status: "PLAYED",
    mupDocument: null,
  },
];
