export const matches = [
  {
    id: 1,
    leagueId: 1,
    homeTeamId: 1,
    awayTeamId: 2,
    date: "2025-03-22",
    time: "15:00",
    location: "Čair",
    round: 12,
    refereeId: 2,
    status: "scheduled",
    mupDocument: null,
  },
  {
    id: 2,
    leagueId: 1,
    homeTeamId: 3,
    awayTeamId: 1,
    date: "2025-03-29",
    time: "16:00",
    location: "Pirot",
    round: 13,
    refereeId: null,
    status: "pending",
    mupDocument: null,
  },
];
