export const players = [
  {
    id: 1,
    firstName: "Nikola",
    lastName: "Nikolić",
    teamId: 1,
    number: 9,
    position: "FW",
    active: true,
    type: "PLAYER",
  },
  {
    id: 2,
    firstName: "Marko",
    lastName: "Marković",
    teamId: 1,
    number: 11,
    position: "MF",
    active: true,
    type: "PLAYER",
  },
  {
    id: 3,
    firstName: "Stefan",
    lastName: "Stojanović",
    teamId: 2,
    number: 7,
    position: "DF",
    active: true,
    type: "PLAYER",
  },
  {
    id: 4,
    firstName: "Aleksa",
    lastName: "Alić",
    teamId: 1,
    number: 9,
    position: "FW",
    active: true,
    type: "PLAYER",
  },
  {
    id: 5,
    firstName: "Milan",
    lastName: "Milanović",
    teamId: 2,
    number: 11,
    position: "MF",
    active: true,
    type: "PLAYER",
  },
  {
    id: 6,
    firstName: "Sadad",
    lastName: "Sadadvić",
    teamId: 3,
    number: 7,
    position: "DF",
    active: true,
    type: "PLAYER",
  },
  {
    id: 7,
    firstName: "Milan",
    lastName: "Jovanović",
    teamId: 1,
    type: "STAFF",
    staffRole: "HEAD_COACH",
    active: true,
  },
  {
    id: 8,
    firstName: "Petar",
    lastName: "Petrović",
    teamId: 1,
    type: "STAFF",
    staffRole: "PHYSIO",
    active: true,
  },
];
