export const teamMembers = [
  {
    id: 1,
    firstName: "Nikola",
    lastName: "Nikolic",
    teamId: 1,
    number: 9,
    position: "FW",
    active: true,
    type: "PLAYER",
  },
  {
    id: 2,
    firstName: "Marko",
    lastName: "Markovic",
    teamId: 1,
    number: 11,
    position: "MF",
    active: true,
    type: "PLAYER",
  },
  {
    id: 3,
    firstName: "Stefan",
    lastName: "Stojanovic",
    teamId: 2,
    number: 7,
    position: "DF",
    active: true,
    type: "PLAYER",
  },
  {
    id: 4,
    firstName: "Aleksa",
    lastName: "Alic",
    teamId: 1,
    number: 9,
    position: "FW",
    active: true,
    type: "PLAYER",
  },
  {
    id: 5,
    firstName: "Milan",
    lastName: "Milanovic",
    teamId: 2,
    number: 11,
    position: "MF",
    active: true,
    type: "PLAYER",
  },
  {
    id: 6,
    firstName: "Sadad",
    lastName: "Sadadvic",
    teamId: 3,
    number: 7,
    position: "DF",
    active: true,
    type: "PLAYER",
  },
  {
    id: 7,
    firstName: "Milan",
    lastName: "Jovanovic",
    teamId: 1,
    type: "STAFF",
    staffRole: "HEAD_COACH",
    active: true,
  },
  {
    id: 8,
    firstName: "Petar",
    lastName: "Petrovic",
    teamId: 1,
    type: "STAFF",
    staffRole: "PHYSIO",
    active: true,
  },
];
